"""initial schema

Revision ID: fc15b2062d40
Revises: 
Create Date: 2026-09-29 20:39:28.255601

"""
from collections.abc import Sequence

import pgvector.sqlalchemy.vector
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'fc15b2062d40'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb")
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('defects',
    sa.Column('defect_code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('defect_code', name=op.f('pk_defects'))
    )
    op.create_table('equipment',
    sa.Column('equipment_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('equipment_type', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=True),
    sa.Column('production_line', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('health_score', sa.Integer(), nullable=False),
    sa.Column('commissioned_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('equipment_id', name=op.f('pk_equipment'))
    )
    op.create_index(op.f('ix_equipment_equipment_type'), 'equipment', ['equipment_type'], unique=False)
    op.create_index(op.f('ix_equipment_production_line'), 'equipment', ['production_line'], unique=False)
    op.create_table('process_parameters',
    sa.Column('line_id', sa.String(length=32), nullable=False),
    sa.Column('parameter_name', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('quality', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('line_id', 'parameter_name', 'timestamp', name=op.f('pk_process_parameters'))
    )
    op.create_table('sensor_readings',
    sa.Column('equipment_id', sa.String(length=32), nullable=False),
    sa.Column('sensor_type', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('quality', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('equipment_id', 'sensor_type', 'timestamp', name=op.f('pk_sensor_readings'))
    )
    op.create_index('ix_sensor_readings_sensor_time', 'sensor_readings', ['sensor_type', 'timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=True),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    op.create_table('agent_sessions',
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_agent_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_agent_sessions'))
    )
    op.create_table('alarms',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('alarm_code', sa.String(length=16), nullable=False),
    sa.Column('equipment_id', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cleared_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], name=op.f('fk_alarms_equipment_id_equipment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alarms'))
    )
    op.create_index(op.f('ix_alarms_alarm_code'), 'alarms', ['alarm_code'], unique=False)
    op.create_index('ix_alarms_equipment_time', 'alarms', ['equipment_id', 'occurred_at'], unique=False)
    op.create_table('documents',
    sa.Column('document_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('document_type', sa.String(length=32), nullable=False),
    sa.Column('equipment_type', sa.String(length=32), nullable=True),
    sa.Column('equipment_model', sa.String(length=64), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('uploaded_by', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_documents_uploaded_by_users')),
    sa.PrimaryKeyConstraint('document_id', name=op.f('pk_documents'))
    )
    op.create_index(op.f('ix_documents_document_type'), 'documents', ['document_type'], unique=False)
    op.create_table('maintenance_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('equipment_id', sa.String(length=32), nullable=False),
    sa.Column('maintenance_type', sa.String(length=16), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('actions', sa.Text(), nullable=True),
    sa.Column('technician', sa.String(length=64), nullable=True),
    sa.Column('related_alarm_code', sa.String(length=16), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], name=op.f('fk_maintenance_records_equipment_id_equipment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_maintenance_records'))
    )
    op.create_index('ix_maintenance_equipment_time', 'maintenance_records', ['equipment_id', 'occurred_at'], unique=False)
    op.create_table('product_batches',
    sa.Column('batch_id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('equipment_id', sa.String(length=32), nullable=False),
    sa.Column('production_line', sa.String(length=32), nullable=False),
    sa.Column('shift', sa.String(length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], name=op.f('fk_product_batches_equipment_id_equipment')),
    sa.PrimaryKeyConstraint('batch_id', name=op.f('pk_product_batches'))
    )
    op.create_index('ix_batches_product_time', 'product_batches', ['product_id', 'started_at'], unique=False)
    op.create_table('agent_messages',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('agent_name', sa.String(length=32), nullable=True),
    sa.Column('tool_name', sa.String(length=64), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.session_id'], name=op.f('fk_agent_messages_session_id_agent_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_messages'))
    )
    op.create_index(op.f('ix_agent_messages_session_id'), 'agent_messages', ['session_id'], unique=False)
    op.create_table('analysis_tasks',
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('task_type', sa.String(length=32), nullable=False),
    sa.Column('equipment_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('input', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], name=op.f('fk_analysis_tasks_equipment_id_equipment')),
    sa.ForeignKeyConstraint(['session_id'], ['agent_sessions.session_id'], name=op.f('fk_analysis_tasks_session_id_agent_sessions')),
    sa.PrimaryKeyConstraint('task_id', name=op.f('pk_analysis_tasks'))
    )
    op.create_table('document_chunks',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.BigInteger(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('token_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.document_id'], name=op.f('fk_document_chunks_document_id_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_document_chunks')),
    sa.UniqueConstraint('document_id', 'chunk_index', name='uq_document_chunks_doc_index')
    )
    op.create_table('quality_inspections',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('batch_id', sa.String(length=32), nullable=False),
    sa.Column('product_id', sa.String(length=32), nullable=False),
    sa.Column('equipment_id', sa.String(length=32), nullable=False),
    sa.Column('shift', sa.String(length=16), nullable=False),
    sa.Column('inspection_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('result', sa.String(length=8), nullable=False),
    sa.Column('defect_type', sa.String(length=32), nullable=True),
    sa.Column('process_temperature', sa.Float(), nullable=True),
    sa.Column('process_pressure', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['product_batches.batch_id'], name=op.f('fk_quality_inspections_batch_id_product_batches')),
    sa.ForeignKeyConstraint(['defect_type'], ['defects.defect_code'], name=op.f('fk_quality_inspections_defect_type_defects')),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], name=op.f('fk_quality_inspections_equipment_id_equipment')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_quality_inspections'))
    )
    op.create_index('ix_inspections_equipment_time', 'quality_inspections', ['equipment_id', 'inspection_time'], unique=False)
    op.create_index('ix_inspections_product_time', 'quality_inspections', ['product_id', 'inspection_time'], unique=False)
    op.create_table('reports',
    sa.Column('report_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('report_type', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('equipment_id', sa.String(length=32), nullable=True),
    sa.Column('risk_level', sa.String(length=16), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('content_markdown', sa.Text(), nullable=True),
    sa.Column('content_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('file_path', sa.String(length=512), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.equipment_id'], name=op.f('fk_reports_equipment_id_equipment')),
    sa.ForeignKeyConstraint(['task_id'], ['analysis_tasks.task_id'], name=op.f('fk_reports_task_id_analysis_tasks')),
    sa.PrimaryKeyConstraint('report_id', name=op.f('pk_reports'))
    )
    # ### end Alembic commands ###

    # TimescaleDB hypertables（架构 §8：统一长表时序模型）
    op.execute(
        "SELECT create_hypertable('sensor_readings', 'timestamp', if_not_exists => TRUE)"
    )
    op.execute(
        "SELECT create_hypertable('process_parameters', 'timestamp', if_not_exists => TRUE)"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reports')
    op.drop_index('ix_inspections_product_time', table_name='quality_inspections')
    op.drop_index('ix_inspections_equipment_time', table_name='quality_inspections')
    op.drop_table('quality_inspections')
    op.drop_table('document_chunks')
    op.drop_table('analysis_tasks')
    op.drop_index(op.f('ix_agent_messages_session_id'), table_name='agent_messages')
    op.drop_table('agent_messages')
    op.drop_index('ix_batches_product_time', table_name='product_batches')
    op.drop_table('product_batches')
    op.drop_index('ix_maintenance_equipment_time', table_name='maintenance_records')
    op.drop_table('maintenance_records')
    op.drop_index(op.f('ix_documents_document_type'), table_name='documents')
    op.drop_table('documents')
    op.drop_index('ix_alarms_equipment_time', table_name='alarms')
    op.drop_index(op.f('ix_alarms_alarm_code'), table_name='alarms')
    op.drop_table('alarms')
    op.drop_table('agent_sessions')
    op.drop_table('users')
    op.drop_table('sensor_readings')
    op.drop_table('process_parameters')
    op.drop_index(op.f('ix_equipment_production_line'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_equipment_type'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_table('defects')
    # ### end Alembic commands ###
